### ISSUE TITLE
docker compose for just headscale-admin?

### ISSUE THREAD

**Issue by europacafe** [GoodiesHQ/headscale-admin#18]
Hi,
I'm now using a a docker compose file to run both headscale server and headscale-webui.
I usually run headscale-webui with its local IP, because I don't want to expose the UI on the internet.
I want to try your headscale-admin alongside the current headscale-webui without having to touch my current docker compose file.

If I create another docker compose file just for the headscale-admin, could you guide me on what to put in the compose file? 
I have tried with below compose, but I only got the settings page (http://localip:8881/admin), and after inputting my headscale server URL (https://headscale.mydomain.com) and a newly generated apikey, it goes nowhere.
```
version: '3.9'
services:
  headscale-admin:
    image: goodieshq/headscale-admin:latest
    container_name: headscale-admin
    restart: unless-stopped
    networks:
      - headscale_default
    ports:
      - 8881:80
    environment:
      - ENDPOINT=/admin   #default: /admin
networks:
  headscale_default:
    external: true
```

Thank you.
