### ISSUE TITLE
Unable to get policy from server.: loading ACL from database: acl policy not found

### ISSUE THREAD

**Issue by mrboros** [GoodiesHQ/headscale-admin#58]
Hello!

First I'd like to thank for all your effort into making this wonderful tool for administering headscale!

I have a problem regarding ACLs. I've already set "policy > mode: database" in headscale's config.yml. When I open headscale-admin and click on "ACL" I get an error mesage: "Unable to get policy from server.: loading ACL from database: acl policy not found".

When I try to load a config from huJSON (like a default allow-all policy from tailnet docs) and click "Save config" I get a "Load failed" error.

Here's how I deploy headscale in different compose units (on different hosts):

Headscale:

```
services:
  headscale:
    image: headscale/headscale:v0.24.3
    restart: unless-stopped
    container_name: headscale
    environment:
      - TZ=Europe/Budapest
    volumes:
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
      - ./run:/var/run/headscale
    command: serve
```

Headscale Admin:

```
services:
  headscale-admin:
    image: custom/headscale-admin:v0.24.8
    container_name: headscale-admin
    restart: unless-stopped
```

Headscale's config.yml (relevant part):

```
...
policy:
  mode: database
  #path: "/var/lib/headscale/acl.json"
...
```

Please help me sort these thing out. Am I doing wrong something?

Thanks
