### ISSUE TITLE
"/api/v1/policy" return "500 Internal Server Error"

### ISSUE THREAD

**Issue by heroes1412** [GoodiesHQ/headscale-admin#74]
im running headscale-admin [v0.25.6](https://github.com/GoodiesHQ/headscale-admin/releases/tag/v0.25.6)
headscale latest version

19:09:00 failed to get policy: Error: loading ACL from database: acl policy not found

every task in ACL menu not work. please check and fix
```
version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      # - "80:80"
      - "60000:60000"
    volumes:
      - /opt/headscale/nginx.headscale.conf:/etc/nginx/conf.d/headscale.conf
      - /opt/headscale/ssl:/etc/nginx/ssl
    depends_on:
      - headscale
      - headscale-admin
    restart: unless-stopped
    networks:
      - headscale-network
        
  headscale:
    image: headscale/headscale
    restart: unless-stopped
    container_name: headscale
    #ports:
    #  - "8888:8888"
    volumes:
      # Please change <CONFIG_PATH> to the fullpath of the config folder just created
      - /opt/headscale:/etc/headscale
      - /opt/headscale/db:/var/lib/headscale
      - /opt/headscale/ssl:/etc/headscale/ssl
    command: serve
    networks:
      - headscale-network  

  derper:
    image: h2372/derper
    container_name: derper
    ports:
      - "8443:8443"  # DERP HTTPS
      - "3478:3478/udp"  # STUN cho DERP
    volumes:
      - /opt/headscale/ssl/domain.xyz.crt:/app/certs/headscale.domain.xyz.crt
      - /opt/headscale/ssl/domain.xyz.key:/app/certs/headscale.domain.xyz.key
    environment:
      - DERP_CERT_MODE=manual
      - DERP_DOMAIN=headscale.domain.xyz
      - DERP_ADDR=:8443
    restart: unless-stopped

  headscale-admin:
    image: goodieshq/headscale-admin:latest
    container_name: headscale-admin
    # ports:
    #  - "8445:80"
    restart: unless-stopped
    networks:
      - headscale-network

networks:
  headscale-network:
    driver: bridge
```
